### PR TITLE
Adding nominees endpoint

### LINKED ISSUE #5: Add endpoint to save the nominees

### LINKED ISSUE #12: Add publish functionality
Receive POST request to publish and save in the Shops collection

### PR DESCRIPTION
**Pull request by bverussa**
Closes #5 
Closes #12

### CODE REVIEW

**Comment by bverussa** [comment]
I rebased my changes with @devfernandoaraujo changes and:
- Rename shop history model to match with the other models
- Add email to the nominee model
- Add publish route to nominee route
- Changes shop model to active be false by default (just publish will set it to true so far)
- Creates shop controller and move the login from routers to the new controller.
- Changes shop router just to be the router itself.

**Comment by bverussa** [comment]
Hey @emersonmellado @devfernandoaraujo @tonykieling 
May you guys review my changes?

**Comment by bverussa** [comment]
@devfernandoaraujo I did the changes. Thanks.

**Comment by emersonmellado** [comment]
I really like this pattern, pretty clean and straight forward! Great job Bruno!

**Pull request merged**
